#include <stdio.h>

struct battery 
{
    int psi;
    int bars;
};

void psi_volt(struct battery charge);
void bar_volt(struct battery charge);

void main() 
{
    struct battery charge;
    int a;

    printf("Choose the unit psi(1) or bars(0): ");
    scanf("%d", &a);

    if(a == 1) 
    {
        printf("Enter the psi range between 0-200: ");
        scanf("%d", &charge.psi);
        psi_volt(charge);  
    } 
    else 
    {
        printf("Enter the bars range: ");
        scanf("%d", &charge.bars);
        bar_volt(charge);  
    }

}

void psi_volt(struct battery charge) 
{
    int voltage = charge.psi / 20;  
    printf("The voltage generated by sensor (from PSI): %d volts\n", voltage);
}

void bar_volt(struct battery charge) 
{
    int voltage = charge.bars * 10;  
    printf("The voltage generated by sensor (from bars): %d volts\n", voltage);
}
